-------------------------------------------------------------------------------
Test set: org.apache.hadoop.fs.ozone.TestRootedOzoneFileSystemWithFSO
-------------------------------------------------------------------------------
Tests run: 86, Failures: 1, Errors: 1, Skipped: 18, Time elapsed: 180.028 s <<< FAILURE! - in org.apache.hadoop.fs.ozone.TestRootedOzoneFileSystemWithFSO
TestRootedOzoneFileSystemWithFSO.testDeleteVolumeAndBucket  Time elapsed: 1.159 s  <<< ERROR!
org.apache.hadoop.fs.PathIsNotEmptyDirectoryException: `/volume-70220/bucket3': Directory is not empty
	at org.apache.hadoop.fs.ozone.BasicRootedOzoneFileSystem.delete(BasicRootedOzoneFileSystem.java:658)
	at org.apache.hadoop.fs.ozone.BasicRootedOzoneFileSystem.delete(BasicRootedOzoneFileSystem.java:618)
	at org.apache.hadoop.fs.ozone.TestRootedOzoneFileSystemWithFSO.testDeleteVolumeAndBucket(TestRootedOzoneFileSystemWithFSO.java:223)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)

TestRootedOzoneFileSystemWithFSO.testListStatusRootAndVolumeNonRecursive  Time elapsed: 0.422 s  <<< FAILURE!
java.lang.AssertionError: expected:<3> but was:<4>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at org.apache.hadoop.fs.ozone.TestRootedOzoneFileSystem.testListStatusRootAndVolumeNonRecursive(TestRootedOzoneFileSystem.java:1012)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)

