2022-10-07 01:09:19,413 | INFO  | OMAudit | user=hadoop | ip=10.9.0.17 | op=GET_SERVICE_LIST {} | ret=SUCCESS |  
2022-10-07 01:09:23,311 | INFO  | OMAudit | user=hadoop | ip=10.9.0.17 | op=GET_SERVICE_LIST {} | ret=SUCCESS |  
2022-10-07 01:09:25,605 | INFO  | OMAudit | user=hadoop | ip=10.9.0.17 | op=GET_SERVICE_LIST {} | ret=SUCCESS |  
2022-10-07 01:09:25,745 | ERROR | OMAudit | user=hadoop | ip=10.9.0.17 | op=READ_VOLUME {volume=34680-volume-for-prepare} | ret=FAILURE | VOLUME_NOT_FOUND org.apache.hadoop.ozone.om.exceptions.OMException: Volume 34680-volume-for-prepare is not found
	at org.apache.hadoop.ozone.om.VolumeManagerImpl.getVolumeInfo(VolumeManagerImpl.java:74)
	at org.apache.hadoop.ozone.om.OzoneManager.getVolumeInfo(OzoneManager.java:2619) 
2022-10-07 01:09:27,955 | INFO  | OMAudit | user=hadoop | ip=10.9.0.17 | op=GET_SERVICE_LIST {} | ret=SUCCESS |  
2022-10-07 01:09:28,092 | INFO  | OMAudit | user=hadoop | ip=10.9.0.17 | op=LIST_VOLUMES {prevKey=, prefix=, maxKeys=1000, username=hadoop} | ret=SUCCESS |  
2022-10-07 01:09:28,359 | INFO  | OMAudit | user=hadoop | ip=10.9.0.17 | op=LIST_VOLUMES {prevKey=vol1, prefix=, maxKeys=1000, username=hadoop} | ret=SUCCESS |  
